/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    certificates: Certificate;
    posts: Post;
    'export-markets': ExportMarket;
    'production-steps': ProductionStep;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'export-markets': ExportMarketsSelect<false> | ExportMarketsSelect<true>;
    'production-steps': ProductionStepsSelect<false> | ProductionStepsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ko' | 'ja') | ('en' | 'ko' | 'ja')[];
  globals: {
    settings: Setting;
    home: Home;
    pages: Page;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
  };
  locale: 'en' | 'ko' | 'ja';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Mô tả ảnh (alt text) cho SEO & trình đọc màn hình.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Định danh trên URL, vd: coconut-shell-charcoal (không dấu, không khoảng trắng).
   */
  slug: string;
  /**
   * Thứ tự hiển thị (số nhỏ hiện trước).
   */
  order?: number | null;
  shortDescription?: string | null;
  image?: (number | null) | Media;
  /**
   * Tiêu đề & mô tả cho công cụ tìm kiếm. Bỏ trống sẽ tự dùng nội dung mặc định.
   */
  seo?: {
    /**
     * Meta title (≈ 60 ký tự).
     */
    title?: string | null;
    /**
     * Meta description (≈ 160 ký tự).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  category?: (number | null) | Category;
  /**
   * Định danh trên URL. Bỏ trống sẽ tự tạo từ tiêu đề.
   */
  slug: string;
  /**
   * Mô tả ngắn hiển thị ở thẻ listing.
   */
  shortDescription?: string | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Bảng thông số. Bỏ trống dòng nào thì dòng đó ẩn ngoài site.
   */
  specs?: {
    /**
     * Fixed Carbon %
     */
    fixedCarbon?: string | null;
    /**
     * Ash %
     */
    ash?: string | null;
    /**
     * Moisture %
     */
    moisture?: string | null;
    /**
     * Volatile Matter %
     */
    volatileMatter?: string | null;
    /**
     * kcal/kg
     */
    calorificValue?: string | null;
    burningTime?: string | null;
    dimensions?: string | null;
    packing?: string | null;
    /**
     * Minimum Order Quantity
     */
    moq?: string | null;
    /**
     * Loading Port / FCL capacity
     */
    loadingPort?: string | null;
    /**
     * HS Code (không cần localize).
     */
    hsCode?: string | null;
  };
  /**
   * File PDF spec sheet cho nút "Download Spec Sheet".
   */
  specSheetPdf?: (number | null) | Media;
  applications?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Nội dung mô tả chi tiết (tùy chọn).
   */
  richContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tiêu đề & mô tả cho công cụ tìm kiếm. Bỏ trống sẽ tự dùng nội dung mặc định.
   */
  seo?: {
    /**
     * Meta title (≈ 60 ký tự).
     */
    title?: string | null;
    /**
     * Meta description (≈ 160 ký tự).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  title: string;
  /**
   * Loại chứng chỉ, vd: ISO 9001, SGS Test, Phytosanitary.
   */
  type?: string | null;
  /**
   * Ảnh hoặc PDF của chứng chỉ.
   */
  file?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Định danh trên URL. Bỏ trống sẽ tự tạo từ tiêu đề.
   */
  slug: string;
  publishedDate?: string | null;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  richContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tiêu đề & mô tả cho công cụ tìm kiếm. Bỏ trống sẽ tự dùng nội dung mặc định.
   */
  seo?: {
    /**
     * Meta title (≈ 60 ký tự).
     */
    title?: string | null;
    /**
     * Meta description (≈ 160 ký tự).
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "export-markets".
 */
export interface ExportMarket {
  id: number;
  country: string;
  /**
   * Mã ISO 2 ký tự (vd: KR, JP, US) — dùng cho cờ/bản đồ. Không cần localize.
   */
  countryCode?: string | null;
  /**
   * Khu vực, vd: East Asia, Middle East, Europe.
   */
  region?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-steps".
 */
export interface ProductionStep {
  id: number;
  /**
   * Thứ tự bước (1, 2, 3...).
   */
  order: number;
  title: string;
  image?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  /**
   * Vòng đời lead — tự cập nhật theo mức độ hoàn thiện form.
   */
  status?: ('partial' | 'qualified' | 'complete') | null;
  /**
   * Trạng thái xử lý của sales (tự điền).
   */
  salesStage?: ('new' | 'contacted' | 'quoted' | 'closed') | null;
  qualified?: boolean | null;
  /**
   * Đã gửi email báo sales cho phiên này chưa.
   */
  notified?: boolean | null;
  /**
   * Đã đẩy dòng qualified sang Google Sheet (qua Make) chưa — tránh gửi trùng.
   */
  pushedToSheet?: boolean | null;
  /**
   * Định danh phiên khách (chống trùng).
   */
  sessionId?: string | null;
  /**
   * Trang khách điền form.
   */
  sourcePage?: string | null;
  lastUpdated?: string | null;
  locale?: string | null;
  product?: string | null;
  /**
   * Quantity / month
   */
  quantity?: string | null;
  destinationPort?: string | null;
  incoterm?: string | null;
  packaging?: string | null;
  targetPrice?: string | null;
  name?: string | null;
  company?: string | null;
  email?: string | null;
  phone?: string | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'export-markets';
        value: number | ExportMarket;
      } | null)
    | ({
        relationTo: 'production-steps';
        value: number | ProductionStep;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  shortDescription?: T;
  image?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  slug?: T;
  shortDescription?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        fixedCarbon?: T;
        ash?: T;
        moisture?: T;
        volatileMatter?: T;
        calorificValue?: T;
        burningTime?: T;
        dimensions?: T;
        packing?: T;
        moq?: T;
        loadingPort?: T;
        hsCode?: T;
      };
  specSheetPdf?: T;
  applications?:
    | T
    | {
        item?: T;
        id?: T;
      };
  richContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  file?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedDate?: T;
  excerpt?: T;
  coverImage?: T;
  richContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "export-markets_select".
 */
export interface ExportMarketsSelect<T extends boolean = true> {
  country?: T;
  countryCode?: T;
  region?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-steps_select".
 */
export interface ProductionStepsSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  status?: T;
  salesStage?: T;
  qualified?: T;
  notified?: T;
  pushedToSheet?: T;
  sessionId?: T;
  sourcePage?: T;
  lastUpdated?: T;
  locale?: T;
  product?: T;
  quantity?: T;
  destinationPort?: T;
  incoterm?: T;
  packaging?: T;
  targetPrice?: T;
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Tên brand hiển thị. Bỏ trống -> dùng tên mặc định.
   */
  companyName?: string | null;
  /**
   * Năm thành lập (hero "…since 20XX").
   */
  foundedYear?: number | null;
  /**
   * Logo. Bỏ trống -> hiện tên công ty dạng chữ.
   */
  logo?: (number | null) | Media;
  /**
   * Slogan ngắn hiển thị ở footer.
   */
  tagline?: string | null;
  legalEntity?: {
    /**
     * Tên pháp nhân đầy đủ.
     */
    name?: string | null;
    /**
     * Mã số doanh nghiệp.
     */
    businessCode?: string | null;
    /**
     * Mã số thuế.
     */
    taxCode?: string | null;
  };
  /**
   * Email nhận đơn RFQ (dạng sales@domain). KHÔNG dùng gmail cá nhân.
   */
  salesEmail?: string | null;
  /**
   * Số WhatsApp dạng quốc tế, vd +84901234567 (dùng cho nút nổi & link).
   */
  whatsappNumber?: string | null;
  phone?: string | null;
  offices?:
    | {
        /**
         * Vd: Head Office, Factory.
         */
        label?: string | null;
        address?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('facebook' | 'linkedin' | 'instagram' | 'youtube' | 'alibaba' | 'whatsapp' | 'other') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Con số uy tín hiển thị dưới hero. Bỏ trống ô nào thì ẩn ô đó.
   */
  trustBar?: {
    /**
     * Vd: 80+
     */
    containersPerMonth?: string | null;
    /**
     * Số quốc gia xuất khẩu, vd: 15+
     */
    countries?: string | null;
    /**
     * Vd: ISO 9001, SGS
     */
    certsNote?: string | null;
    /**
     * Vd: 12+
     */
    yearsExporting?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero?: {
    /**
     * Bật/tắt hiển thị section này ngoài trang chủ.
     */
    enabled?: boolean | null;
    kicker?: string | null;
    title?: string | null;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
    ctaPrimaryLabel?: string | null;
    ctaSecondaryLabel?: string | null;
  };
  trustBar?: {
    /**
     * Bật/tắt hiển thị section này ngoài trang chủ.
     */
    enabled?: boolean | null;
  };
  productGroups?: {
    /**
     * Bật/tắt hiển thị section này ngoài trang chủ.
     */
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
  };
  factory?: {
    /**
     * Bật/tắt hiển thị section này ngoài trang chủ.
     */
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    /**
     * Link YouTube/Vimeo (tùy chọn).
     */
    videoUrl?: string | null;
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  certificates?: {
    /**
     * Bật/tắt hiển thị section này ngoài trang chủ.
     */
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
  };
  exportMap?: {
    /**
     * Bật/tắt hiển thị section này ngoài trang chủ.
     */
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
  };
  buyingProcess?: {
    /**
     * Bật/tắt hiển thị section này ngoài trang chủ.
     */
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    steps?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  faq?: {
    /**
     * Bật/tắt hiển thị section này ngoài trang chủ.
     */
    enabled?: boolean | null;
    title?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  rfqCta?: {
    /**
     * Bật/tắt hiển thị section này ngoài trang chủ.
     */
    enabled?: boolean | null;
    title?: string | null;
    subtitle?: string | null;
    buttonLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  about?: {
    title?: string | null;
    subtitle?: string | null;
    coverImage?: (number | null) | Media;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Hiện khối thông tin pháp nhân/văn phòng (lấy từ Settings).
     */
    showCompanyDetails?: boolean | null;
  };
  oem?: {
    title?: string | null;
    subtitle?: string | null;
    coverImage?: (number | null) | Media;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    features?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    gallery?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  companyName?: T;
  foundedYear?: T;
  logo?: T;
  tagline?: T;
  legalEntity?:
    | T
    | {
        name?: T;
        businessCode?: T;
        taxCode?: T;
      };
  salesEmail?: T;
  whatsappNumber?: T;
  phone?: T;
  offices?:
    | T
    | {
        label?: T;
        address?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  trustBar?:
    | T
    | {
        containersPerMonth?: T;
        countries?: T;
        certsNote?: T;
        yearsExporting?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        enabled?: T;
        kicker?: T;
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        ctaPrimaryLabel?: T;
        ctaSecondaryLabel?: T;
      };
  trustBar?:
    | T
    | {
        enabled?: T;
      };
  productGroups?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
      };
  factory?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        videoUrl?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  certificates?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
      };
  exportMap?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
      };
  buyingProcess?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        enabled?: T;
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  rfqCta?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  about?:
    | T
    | {
        title?: T;
        subtitle?: T;
        coverImage?: T;
        body?: T;
        showCompanyDetails?: T;
      };
  oem?:
    | T
    | {
        title?: T;
        subtitle?: T;
        coverImage?: T;
        body?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}